workflows:
  ios-workflow:
    name: Build iOS IPA for Swipeology
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SWIPEOLOGY
    environment:
      vars:
        NODE_OPTIONS: "--max-old-space-size=4096"
        BUNDLE_ID: "app.rork.swipeology-dating-app"
        XCODE_WORKSPACE: "ios/SwipeologyDatingApp.xcworkspace"
        XCODE_SCHEME: "SwipeologyDatingApp"
      node: 20
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Prebuild native iOS project
        script: |
          npx expo prebuild --clean --platform ios
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch/create certificates and profiles
        script: |
          # This will create certificate AND provisioning profile
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
