workflows: 
  ios-workflow: 
    name: Build iOS IPA for Swipeology
    environment: 
      vars: 
        NODE_OPTIONS: "--max-old-space-size=4096" 
      node: 20 
      cocoapods: default 
    scripts: 
      - name: Install dependencies 
        script: | 
          npm install 
      - name: Prebuild native iOS project 
        script: | 
          npx expo prebuild --clean --platform ios 
      - name: Build iOS archive 
        script: | 
           xcodebuild -workspace ios/SwipeologyDatingApp.xcworkspace \
            -scheme SwipeologyDatingApp \
            -configuration Release \
            -archivePath build/SwipeologyDatingApp.xcarchive \
            archive
      - name: Export IPA 
        script: | 
          xcodebuild \ 
            -exportArchive \ 
            -archivePath build/SwipeologyDatingApp.xcarchive \ 
            -exportOptionsPlist ios/exportOptions.plist \ 
            -exportPath build 
    artifacts: 
      - build/*.ipa 
      - build/**/*.dSYM 
      - build/**/*.xcarchive
